name: Promote artifact

on:
  workflow_call:
    inputs:
      group:
        description: "Maven group"
        required: true
        type: string
      artifact:
        description: "Maven artifact"
        required: true
        type: string
      version:
        description: "Maven version"
        required: true
        type: string
      type:
        description: "Promotion type"
        required: false
        type: string
        default: "latest"
    secrets:
      PAGEGEN_WEBHOOK:
        required: true
      PAGEGEN_USERNAME:
        required: true
      PAGEGEN_PASSWORD:
        required: true

  workflow_dispatch:
    inputs:
      group:
        description: "Maven group"
        required: true
        type: string
      artifact:
        description: "Maven artifact"
        required: true
        type: string
      version:
        description: "Maven version"
        required: true
        type: string
      type:
        description: "Promotion type"
        required: false
        type: choice
        default: "latest"
        options:
          - "latest"
          - "recommended"

jobs:
  promote-artifact:
    name: Promote artifact
    runs-on: ubuntu-latest
    steps:
      - name: Create JSON
        id: create-json
        uses: actions/github-script@v6
        env:
          group: ${{ inputs.group }}
          artifact: ${{ inputs.artifact }}
          version: ${{ inputs.version }}
          type: ${{ inputs.type }}
        with:
          result-encoding: string
          # language=js
          script: |
            'use strict';
            const { group, artifact, version, type } = process.env
            const json = {
              group: `${group}`,
              artifact: `${artifact}`,
              version: `${version}`,
              type: `${type}`
            }
            
            return JSON.stringify(json)

      - name: Notify webhook
        # language=bash
        run: |
          curl --tlsv1.3 --compressed -sS -m 10 -u "${{ env.PAGEGEN_USERNAME }}:${{ env.PAGEGEN_PASSWORD }}" -H "Content-Type: application/json" --request POST -d '${{ steps.create-json.outputs.result }}' ${{ env.PAGEGEN_WEBHOOK }}
        env:
          PAGEGEN_WEBHOOK: ${{ secrets.PAGEGEN_WEBHOOK }}
          PAGEGEN_USERNAME: ${{ secrets.PAGEGEN_USERNAME }}
          PAGEGEN_PASSWORD: ${{ secrets.PAGEGEN_PASSWORD }}
